# OAuth Token Expiry Validation Test
Tags: auth

This specification tests token expiry validation when using OAuth tokens with endpoints.

**Prerequisites**: 
- The mock server must be running with REQUIRE_AUTH=true before executing this test
- OAuth tokens must be validated for expiry

* REST server address from environment variable "REST_SERVER_ADDRESS" or default "http://localhost:8080"

## Test token expiry validation with valid token

This test requires REQUIRE_AUTH=true environment variable.

* Start authenticated session
* Generate OAuth token with authorization code "test_valid_token"
* Store access token from OAuth response
* Request video via REST with stored token and id "test-video-1" and parts "snippet"
* Verify REST response status is "200"
* Close the connection

## Test token expiry validation with expired token

This test requires REQUIRE_AUTH=true environment variable.

* Start authenticated session
* Generate OAuth token with authorization code "test_expired_token" and expires in "-60"
* Store access token from OAuth response
* Request video via REST with stored token and id "test-video-1" and parts "snippet"
* Verify REST response status is "401"
* Verify REST error message contains "expired"
* Close the connection

## Test token expiry validation with short-lived token

This test requires REQUIRE_AUTH=true environment variable.

* Start authenticated session
* Generate OAuth token with authorization code "test_short_lived" and expires in "2"
* Store access token from OAuth response
* Request video via REST with stored token and id "test-video-1" and parts "snippet"
* Verify REST response status is "200"
* Wait for "3" seconds
* Request video via REST with stored token and id "test-video-1" and parts "snippet"
* Verify REST response status is "401"
* Verify REST error message contains "expired"
* Close the connection

## Test untracked token passes through

This test requires REQUIRE_AUTH=true environment variable and verifies that random tokens not generated by the mock pass through.

* Start authenticated session
* Use untracked token "random_untracked_token_12345" to request video with id "test-video-1" and parts "snippet"
* Verify REST response status is "200"
* Close the connection
